version: '3.7'
services:
  postgres:
    container_name: security-project
    image: postgres:14
    environment:
      POSTGRES_DB: security-project
      POSTGRES_USER: qaisar
      POSTGRES_PASSWORD: qwerty
      PGDATA: /data/postgres
    volumes:
      - ./volumes/postgres-inventory:/data/postgres
    ports:
      - "5432:5432"
    restart: always

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:23.0.3
    ports:
      - "8181:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: "start-dev"