spring:
  application:
    name: spring-security
  datasource:
    driver-class-name: org.postgresql.Driver
    username: qaisar
    password: qwerty
    url: jdbc:postgresql://localhost:5432/security-project
  jpa:
    hibernate:
      ddl-auto: create-drop
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/eselpo
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8181/realms/eselpo
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: springsecurity
            client-secret: rBvs7awUMaVkf6UWHf3y5qjEaCw5zIZx
            scope: openid
server:
  port: 8081
#logging:
#  level:
#    org.springframework.security: TRACE